### PR TITLE
Code from samsungtv-smart

### PR DESCRIPTION
**Pull request by ollo69**
This PR contains changes implemented in branch [ha-samsungtv-smart](https://github.com/ollo69/ha-samsungtv-smart).

Summary of main changes:

- implemented config_flow: this means that component is not using media_player component but implement an integration with a specific domain. Initial configuration via yaml is not possible anymore, only some parameter can be provided via yaml. This it greatly reduces issues due to incorrect configurations that is quite complex!!!
- SmartThings & uPnP class rewrite: this classes now use aiohttp and all methods are async to be compliant with HA model. Also several bug was fixed in SmartThings.
- Samsung WS global review: the WebSocket connection use 3 different channels (remote, app and FrameTV) and the communication channel with tv is maintained active for all the time that the TV is on. This also solve a lot of problem related to token use and random request of new token on TV and obviously introduce FrameTV control.
- media_player code moved to async: most of the call inside the main module was reviewed to be async, also to avoid continues switch from sync to async that have big impact on performance and in some cases are not properly managed

Scope here is start discussing about changes and determinate how to converge to unique component for Samsung TV.

### CODE REVIEW

**Comment by jaruba** [comment]
I think the most obvious blockers here are the deprecated settings and the introduction of a config flow.

The only way that I can think of in order to move this forward gradually is by adding a "auto" option as the default for the next to be deprecated settings, and merging without the config flow. Depending on the requirements of the SmartThings / Samsung WS improvements of having the config flow, we can decide what we can keep from them for this release. (v1.5.7 -> v1.6.0 ?)

After that we can release a new major version that deprecates those settings too and introduces the config flow. (v1.6.0 -> v2.0.0 ?)

The question is if it's worth the hassle of doing it that way, as we could also just release v2.0.0 directly with all the changes.. although i know you're ( @ollo69 ) not a fan of such a "big bang" approach, I am not entirely convinced of the necessity of an in-between version, as we will release v2.0.0 anyway. Releasing 2 versions instead of one would just make users have to update it 2 times in order to get to the same end version anyway, and probably cause some confusion / frustration along the way too.

The sooner we get this merged, the sooner we can restart work on the component, as working on it now would just cause merge conflicts.

@ollo69 @Screwdgeh would love to hear some thoughts on this

**Comment by Screwdgeh** [comment]
Hey @ollo69 @jaruba ,

I've been offline a lot more since I have a baby daughter now, but in between I did find some time for a bit of testing and doing a bit of code review. 

Huge compliments to the code package by @ollo69! 

I did not get around to testing without smartthings yet, but with it it works like a charm. Some things I would like to improve before we do a release:
- Implement logo feature including config option
- Assume '@Tv' by default when using channel_list
- Add volume up/down buttons to the UI
- Option to change MAC and broadcast_address from option flow
- Review whether it is possible to have a channel list and app list configurable using config/option flow
- Have TV channel change first check on which channel it is on currently to avoid swapping from digital to analog accidentally when changing to the same channel.

Things that can come later:
- Fully async websocket implementation
- Turn on TV first when initiating a change source command while tv is currently off (e.g. via voice assistant)

Shouldn't we just merge this code to the ha-samsungtv-tizen `merge-samsungtv-smart` branch already and all work from there?

I don't see much added value in doing a phase-out and would prefer the big-bang approach as long as we make clear statements in documentation and HACS about what users are required to do. The ease of configuration with the new changes makes it more than worthwhile in my view! Indeed make it v2.0

**Comment by jaruba** [comment]
@Screwdgeh 

> since I have a baby daughter now

Congrats! That's amazing! I'm very happy for u.

I also couldn't dedicate as much time as I wanted to this, but my reasons are more work related and have started a new hobby project that is taking quite a lot of time, although I'm very close to finishing it now.

All ur suggestions are great, and I fully agree with them, we should merge this to a separate branch to work on it properly and release it as v2.0.0 so we reduce user confusion, with a clear statement of the changes that the users should expect when transitioning.

**Comment by ollo69** [comment]
@Screwdgeh 

> I've been offline a lot more since I have a baby daughter now

first of all, congrats, for sure this will take you more time than you expect :)

Coming back to the component, I can agree to release a 2.0 version with all changes, but it's important to clearly explain what will happen. The main problem is that after upgrade to the new version, the component will disappear and must be reconfigured. This will create confusion, especially to user that just upgrade and don't read note.

I agree with some of your suggestion, but not all, here my consideration:   

- Implement logo feature including config option
  Absolutely, already working on this. We cannot miss an existing feature
- Assume '@tv' by default when using channel_list
  Not agree. I try initially to do this but at the end make coding too match complex, and in some case do not make sense. In Italy my first source is the Sky Box, I use antenna in very rare case. The logic that I implemented just say that if source is not present it use current source, and may be is better to enforce with the source mandatory. Default logic always create issues
- Add volume up/down buttons to the UI
  This should be already in place, I see up and down button for my TV. Yo don't?
- Option to change MAC and broadcast_address from option flow
  We can discuss about this. It is not complex to put this in option flow, but I leave it in configuration.yaml because I consider this "advanced option" (not for all). Mac address is normally detected by config flow and default subnet is normally ok. Leave the user to change this is possible but is not simple to control what they are writing
- Review whether it is possible to have a channel list and app list configurable using config/option flow
  This is also possible, but we have to think how this should be managed. Because is a long string, is more simple to edit this in configuration.yaml than in the option flow windows. Other solution should be create something like a wizard that allow you to create the list, but this is quite complex to implement, may be we can leave this as future step.
- Have TV channel change first check on which channel it is on currently to avoid swapping from digital to analog accidentally when changing to the same channel.
   Not clear to me this point, but may be force to always put the source will avoid the issue?
- Fully async websocket implementation
   Not sure this is possible, we should investigate on available library. It is really useful?
- Turn on TV first when initiating a change source command while tv is currently off (e.g. via voice assistant)
   Good idea, already working on this. I will release shortly this change here
- Improve mute check status and set volume in case of an external audio source (currently does not work when having an HDMI ARC devices connected at least)
  Not sure is possible. I also have a sound bar with ARC input, the problem is that is not possible to check the status. We need to investigate.

Let me finish to integrate "logo" with in this branch, than we can merge te PR and choose how to proceed. 
For sure v.2.0 will also require a big review of the documentation. Something could be take from my repository, but for sure can be enhanced (I'm not very good with documentation :))

**Comment by ollo69** [comment]
Additional note: we must create a PR [here](https://github.com/home-assistant/brands) to have the logo displayed in HA integration page. We can use the same logo used by my repository or a new one...

**Comment by jaruba** [comment]
@ollo69 

there was already a PR made for this component's logo at `home-assistant/brands`, and it has been merged on 27 Oct 2020, so we don't need to do that

> Let me finish to integrate "logo" with in this branch, than we can merge te PR and choose how to proceed.

feel free to merge this PR when you are finished

> For sure v.2.0 will also require a big review of the documentation. Something could be take from my repository, but for sure can be enhanced (I'm not very good with documentation :))

although i don't particularly like writing docs, i am good at it, and have written huge docs for SDKs and large APIs in the past, so I will start rewriting the docs after the PR is merged

**Comment by Screwdgeh** [comment]
> * Implement logo feature including config option
>   Absolutely, already working on this. We cannot miss an existing feature

Ohh maybe pull the brakes there! I have code ready that implements logos on top of your current code, ready to commit. Code is as cleanly as possible separated in logo.py to not pollute media_player.py and has config and creation flow handled. OK to merge your PR here already so I can commit on top of it in this project?

> * Assume '@tv' by default when using channel_list
>   Not agree. I try initially to do this but at the end make coding too match complex, and in some case do not make sense. In Italy my first source is the Sky Box, I use antenna in very rare case. The logic that I implemented just say that if source is not present it use current source, and may be is better to enforce with the source mandatory. Default logic always create issues

Hmm ok, maybe people using antenna isn't that common anymore these days! Call me old fashioned :) let's make it mandatory to put a source then as people would easily misunderstand how this works otherwise.

> * Add volume up/down buttons to the UI
>   This should be already in place, I see up and down button for my TV. Yo don't?

Nope... I'll have a look to see if I can understand why!
image

> * Option to change MAC and broadcast_address from option flow
>   We can discuss about this. It is not complex to put this in option flow, but I leave it in configuration.yaml because I consider this "advanced option" (not for all). Mac address is normally detected by config flow and default subnet is normally ok. Leave the user to change this is possible but is not simple to control what they are writing

Yep all right, that's OK for me, keep advanced options to configuration.yaml makes sense, especially if we don't find a way to configure source, app, channel lists via config flow.

> * Review whether it is possible to have a channel list and app list configurable using config/option flow
>   This is also possible, but we have to think how this should be managed. Because is a long string, is more simple to edit this in configuration.yaml than in the option flow windows. Other solution should be create something like a wizard that allow you to create the list, but this is quite complex to implement, may be we can leave this as future step.

Understood... Agree we should only do it if it is user friendly, a single field is not that. I had in mind to have a field per app and channel (apps auto-populated with checkboxes based on installed app list), but understanding the config and option flow better now it's not straightforward to set this up like that... let's leave it for now.

> * Have TV channel change first check on which channel it is on currently to avoid swapping from digital to analog accidentally when changing to the same channel.
>   Not clear to me this point, but may be force to always put the source will avoid the issue?

This is only an issue for those that watch via antenna... It has digital and analog mode and switching to the same channel causes it to switch between the two. This only requires special case handling for 'Tv' source - compare current channel number and avoid changing to it if it is already on that channel. When switching from another source/app it needs to switch first, wait until it knows channel number and then decide to change channel or not. I haven't figured out another way to prevent this from happening.

> * Fully async websocket implementation
>   Not sure this is possible, we should investigate on available library. It is really useful?

I have the skeleton code for this ready using [websockets](https://websockets.readthedocs.io/en/stable/) library... but not as feature rich now as your implementation - it would help with key chaining commands ensuring one command comes truly after by applying a queueing mechanism... Would also I guess bump quality up through being fully async and not working with multiple threads - in case we'd ever like to make this the standard samsung tv component.

> * Turn on TV first when initiating a change source command while tv is currently off (e.g. via voice assistant)
>   Good idea, already working on this. I will release shortly this change here

Awesome, I'll give it a shot once you have implemented!

> * Improve mute check status and set volume in case of an external audio source (currently does not work when having an HDMI ARC devices connected at least)
>   Not sure is possible. I also have a sound bar with ARC input, the problem is that is not possible to check the status. We need to investigate.

I am not sure either, indeed with current UPNP calls it doesn't get the right feedback, as it seems to complain that the 'master' audio channel we are requesting data for is not there or something similar. Maybe there is a call we can use to check the audio channels... or otherwise we should handle the error more gracefully. At the same time we can probably use another UPNP call to perform the same extra check whether TV is online or not instead of mute status check such that it wouldn't fail with an ARC device connected. I'll start looking into this.

> Let me finish to integrate "logo" with in this branch, than we can merge te PR and choose how to proceed.

As said earlier, code proposal for logo is there! If we can merge the PR to samsungtv_tizen first it saves me from forking and making a PR in your project... Are you OK with that?

> For sure v.2.0 will also require a big review of the documentation. Something could be take from my repository, but for sure can be enhanced (I'm not very good with documentation :))

Maybe @jaruba takes the lead on this one and we review/improve/add after a first round?

I did notice one other strange thing while testing. For some reason apps will not launch using this component on one of my TVs. With the current samsungtv_tizen component I do not have that issue. Need to have a further look, maybe an other app launch method works... I'm not sure if it maybe has to do with both the old and new component connecting at the same time. I by the way also discovered how to launch apps via smartthings directly using a custom.launchapp command - if we'd ever need it.

**Comment by ollo69** [comment]
Ok, so let me do final checks, than we can merge PR in this branch and you can PR your logo implementation.
Related to the problem in launching application, did you try to change the launch method in options? The method used in this component should correspond to "Rest API call".
Furthermore, if you have a TV with art_mode, I just implemented a service to set this status. Can you test it?

Good to know that @jaruba will manage documentation...   😊🎉

**Comment by Screwdgeh** [comment]
> Ok, so let me do final checks, than we can merge PR in this branch and you can PR your logo implementation.

I am merging now and will then add the logo implementation on top. Did @jaruba make you a contributor yet so you can commit directly yourself?

> Related to the problem in launching application, did you try to change the launch method in options? The method used in this component should correspond to "Rest API call".

I have seen some inconsistent behavior using websockets. I am not sure if it has to do with multiple components (multiple HA instances connecting at same time). When I choose Rest API call it so far looks reliable.

> Furthermore, if you have a TV with art_mode, I just implemented a service to set this status. Can you test it?

Sadly I don't have this either...

> Good to know that @jaruba will manage documentation... 😊🎉

**Comment by ollo69** [comment]
Yes, I'm contributor, but I still have some change I'm doing in SmartThings.
Anyway start your PR related to logo's, I will create a new PR after for this.
Please give me the option to see the changes related to logo's before merging it

**Comment by ollo69** [comment]
@Screwdgeh,

just one think: I'm finishing implementation to manage picture mode using SmartThings, I think that I will be able to create and merge a PR by tonight. 
Please give me the time to do this before starting with logo part or I will became crazy in merging.

**Comment by Screwdgeh** [comment]
@ollo69 - Damn, I'm sorry I didn't read this on time! I've just committed my changes into the branch. Since the code is quite cleanly separated it's easy for me to make the changes again. 

I reverted my commit and wait for your OK signal after your update.

**Comment by jaruba** [comment]
Regarding The Frame TV, I don't have one either, but the users will complain about it if it doesn't work and we can use their feedback to improve it.

As I'll be rewriting the docs, one problem arises: donations. If we choose to keep a donation link, it should then be on a platform that shows exactly how many donations and the sums we get so they can be split to each. Otherwise, we could just disable donations and that's that. Personally, I don't care much for them, and they will be rare / low sums anyway. They are only good as a motivator IMO, but motivation is needed more when working solo on an open source project compared to working as a team.

Awaiting both ur feedback on this.

**Comment by ollo69** [comment]
> As I'll be rewriting the docs, one problem arises: donations

I don't think that we will get rich with this 😊, doesn't really matter to me.
In my repo I just created a "buy me a coffe" link, and honestly I don't think that I go over 50$ till now (not sure because I have also it on another repo). 
I agree with you that is valid for motivation / gratification for job done, but I totally leave decision in your hand, no problem from my side.

**Comment by jaruba** [comment]
Then if @Screwdgeh also agrees, I would remove the donation link. When I started this repo, the best Samsung TV component was `xchwarze/ha-samsungtv-custom`, i can't even expand on how much this project has grown and what it means to all automation enthusiasts that have Samsung TVs. That and having a team of people dedicated to improving it in the future too is more then enough gratitude for me.

I will try to reach out to xchwarze and roberodin too after we manage to make a new release. Maybe I can convince them to further get behind the idea of one primary component for Samsung TVs, although roberodin's component is meant to support pre-Tizen TVs also, and that would be a radical change if we tried to implement it in this component..

Can't hurt to try to start a discussion with them though.

**Comment by jaruba** [comment]
@Screwdgeh ollo's last PR was merged, you should go ahead with your logo changes when you have some time

**Pull request merged**
