### PR TITLE
SmartThings improvement using aiohttp

### PR DESCRIPTION
**Pull request by ollo69**
SmartThings componenent reviewed to use aiohttp instead requests (more compliant with HA)
Now ST methods are async and media_player module use async call for update.
Next step should be the review of other methods that use requests (as ping and HTTP app list update)
Better to do several test before release this change, performance improvement is important but moving from sync to async may cause some unexpected issues.

### CODE REVIEW

**Comment by jaruba** [comment]
this is gonna be a bitch to test and review

**Comment by ollo69** [comment]
I Know, but solve expecially situation when sometime network connection is not available. Personally I'm running it from a couple of days at it works fine!

**Comment by jaruba** [comment]
I've created a conflict with your PR with this commit: https://github.com/jaruba/ha-samsungtv-tizen/commit/9c37012592c13416183b5bc3cd5e128f51348ec1

**Comment by ollo69** [comment]
Solved the confict

**Comment by ollo69** [comment]
Hi,

For the moment I closed this pull request because I understand that the change done my side is really big, and I still have some idea. 
Anyway I will appreciate any suggestion and help from you in my revision.
My goal is to make configuration as simple as possible, creating a very simple and powerful control.
My next step is to remove also device_name parameter and create a config_flow for installation.

Wait for your feed-back.

Ciao.

**Comment by jaruba** [comment]
Sorry, I don't have much time to look over it now, I will at some point, just probably not this weekend.

**Pull request closed without merging**
