### PR TITLE
Move token file in storage folder

### PR DESCRIPTION
**Pull request by ollo69**
This PR is to move token file in storage folder and generally avoid to write file in the integration folder as suggested in [this issue](https://github.com/ollo69/ha-samsungtv-smart/issues/71). 

@jaruba, any news about documentation, there is something we can do. I understand that you have issue configuring the integration, can we help in some way?

@Screwdgeh, if ok for you, I'm thinking about merging your logo implementation in my fork.

I don't want to quit this migration project, but merging the logo in my fork will help me to maintain this branch aligned in case of issue / improvement and we will be able to start testing the implementation in new component version.

Wait for your feedback,

### CODE REVIEW

**Comment by jaruba** [comment]
@ollo69 

> any news about documentation, there is something we can do. I understand that you have issue configuring the integration, can we help in some way?

That's nice of you to ask, a couple of weeks ago both my TVs went completely offline from SmartThings:
Screenshot_20210410-021910


I've seen the SmartThings API act weirdly for other users too, it was never the most stable API, it usually just came back by itself after some time. I suspected that PiHole and/or AdGuard Home blacklisted some SmartThings API endpoint(s), but I have whitelisted everything that seemed related to it and their still offline. I can try disabling my local DNS servers completely and see how that goes, but for now, whenever I try to install the merge branch it just fails installing, during the installation it says it can't find any of my TVs by their IDs. (the master branch of this component is also non-functioning at this point)

**Comment by jaruba** [comment]
To note, I also tried factory reseting the TVs and they still refuse to connect to SmartThings..

**Comment by ollo69** [comment]
That's terrible, I'm probably lucky because SmartThings works very well for me, but probably this is strongly related to the region. So we can just wait hoping that Samsung will fix this.

**Comment by jaruba** [comment]
It used to work fine for me too, for a very long time, and it just competely broke out of nowhere.

**Comment by jaruba** [comment]
If you want we can just use ur docs and add a note for the logo settings to be able to release. I'll disable the local DNS servers for a week to see if that helps getting them back online. (from research I saw that even if it is a SmartThings blacklisting issue, it takes at least 24h for them to come online due to internal DNS caching in the TVs)

And if they come back online I will rewrite the docs asap. I don't really see an alternative at this point, this issue caught me completely off guard, it's been a long time now and it did not get resolved, I really hope it's a local DNS problem at this point, although it seems unlikely from all the tests I did by now.

**Comment by ollo69** [comment]
I think that we can wait some more time, it is better that at list owner of the component should be able to use it. I would not take the risk that you will open an issue as soon as the new version is released 😁. 
Maybe you can try contacting Samsung support, just to see if they have some suggestion or forecast? This is a customer service and they should provide support for this.

**Comment by jaruba** [comment]
@ollo69

I am happy to announce that I managed to get the Series 7 TV back on SmartThings two days ago and should be able to start work on the docs soon. The Series 6 TV is still unable to connect, I'm a bit worried that they might of phased out support for it or (hopefully just) broke it with an update. It's a 2016 TV if I'm not mistaken.

**Comment by ollo69** [comment]
@jaruba, @Screwdgeh,

today I had time to make some test, I just found a couple of bug (fixed in this PR) and moved the logo download json file to HA storage folder (as best practice we should never write files in code folder).
Everything is working properly, I just found an issue with one app that is not showing logo that is `Prime Video`. I don't go in deep is logo implementation, I just take a look to the file `logo_paths.json` and there I found different alias as `Amazon Prime`, `Prime`, but not `Prime Video` (that I think is the right name for the service). Should this string inserted in the `logo_paths.json`?

**Comment by jaruba** [comment]
@ollo69 you can add any string to the logopaths.json file here: https://github.com/jaruba/channel-logos/blob/main/logo_paths.json

and if it requires a custom logo, that can also be added to the "custom" folder in the same repo (there is a readme in that folder that should explain things clearly)

not sure if prime video will work after that, there are a few samsung tv apps that don't announce anything to the samsung api, such is the case for "Plex" too and a few others.

is this PR ready btw? should i test / merge?

**Comment by ollo69** [comment]
Yes, I think you can test and merge, I'm running with this version now. If I eventually discover new issues I will create a new one. 
I will make some tests with prime video logo on next days and eventually create a PR in your logo repository. I think it should work using Smartthings.

**Comment by jaruba** [comment]
@ollo69 

It's really strange that I only managed to get the Series 7 TV working with SmartThings again btw. On the Series 6 TV I can't even find the SmartThings app in the App Store anymore.. I have to say that I'm pretty worried that Samsung is quietly removing SmartThings API support for older TVs.. and that's just a 2016 (or 2017) TV.. There are huge unanswered threads on the Samsung forums about users that are unable to connect to SmartThings with their TVs anymore, and particular Tizen updates that completely break it for them..

The reason I'm mentioning it is because that will impact this component as well.

**Comment by ollo69** [comment]
With this TV a 5 years old model is considered prehistoric 😁. Unfortunately the market require continuous new models, and life of these devices are limited to few years. My series 7 55" died after about 3 years, now I have a series 8 65" paid less than previous model.
We don't have control on this, we just can support as Samsung do.

**Comment by ollo69** [comment]
With last commit I improved channel logo match with 2 little changes:

- try remove from `media_title` phrases between round brackets 
- try to remove the word `HDTV`

Example: I have one channel that is returned as: `Fox HDTV (Italy)`, so I remove `HDTV` and `(Italy)` and `Fox` logo is matched.

If you have some concern about this last change I can also roll-back it, anyway my side everything is working fine.

**Comment by ollo69** [comment]
@jaruba, @Screwdgeh, 

this project is taking too long and it is too complex for me to continue maintain my integration and this PR without having code aligned.
For this reason I merged my main branch / release version with logo support implemented here, adding credits in readme.
Of course I will continue pushing changes here, and I'm still available to converge to an unique repository when you will be ready.
Please let me know any concern.

**Comment by jaruba** [comment]
@ollo69 Hi, in the meanwhile i have received a lot more responsibility at my job and have other projects that grew and require a lot of my attention as well. At this point the only thing I'm able to do for this project is to make the minor changes that the users discover / request in order to keep it working with the newer HA versions, as I haven't even had time to update HA in the last 6+ months.

When I tested it the last time, I remember that the only thing I didn't enjoy about the PR was that I was unable to add my TVs while there were unknown API issues with them, while this current component is able to add them even if the API connections are down for the TVs (as these issues seem to always be temporary).

With that said, you are welcome to take over this repository if you wish, and retire your fork of it if that is still your plan. As much as I'd want to continue working on this, I really don't have enough time for it anymore at this point and you seem to be the most active developer.

**Comment by ollo69** [comment]
First of all congrats to you and for your job.
At this point I prefer to stay some more time with my fork active aligned with this branch and monitor usage before moving back to this repo. I just want to be sure to not break something that many users still use and leave the option to choose preferred version.
I will merge this PR in this branch for now in, so that I will be able to create new one when required and we will move to master when we will be sure about this.

**Pull request merged**
