### PR TITLE
 Made HA 0.110.0 compatible for deprecated references+ more fixes

### PR DESCRIPTION
**Pull request by mcc05**
As above ready for your testing in HA 0.110.0

### CODE REVIEW

**Comment by mcc05** [comment]
Safe for pre 0.110 HA

**Comment by mcc05** [comment]
Ready for you testing if you like :)

**Comment by jaruba** [comment]
Seems to work fine in my tests, and the code seems pretty safe, merging.

**Comment by jaruba** [comment]
released as v1.4.8

**Pull request merged**
