### PR TITLE
Updated, faster updates and async get applist, and more exception trapping…

### PR DESCRIPTION
**Pull request by mcc05**
NOTE: Changed default update method to websockets

Please merge if you are happy after testing

### CODE REVIEW

**Comment by jaruba** [comment]
Are u sure that the websockets update is better then ping. I've tested all the available update methods in the past and ping seemed to be the most reliable.

I'm also curious why the optimistic setting of the on / off states when triggered from HA was commented out, is there a good reason for that? That also worked pretty well in previous tests.

**Comment by mcc05** [comment]
Fair point, I suppose it just because I've been using web sockets and they seem fine, the optimistic values I took out because the forced update should happen in 100ms, but you are right no harm to have them back in, I'll revert the bits :)

**Comment by mcc05** [comment]
Please test this out an commit if happy :)

**Comment by jaruba** [comment]
Sorry for the long wait on this, I'll be able to test your changes next week.

**Comment by mcc05** [comment]
Heh no problem, just trying to help out :)

**Comment by mcc05** [comment]
Interesting comment in https://community.home-assistant.io/t/improving-samsung-tv-control/151922/266, In this code I put an exception trap around that section as I was getting it on occasion, i'm using _gen_installed_app_list by default should this be trying to build the double ID code list??

**Comment by jaruba** [comment]
Merged, I'll ping you when I've made a new release.

**Comment by jaruba** [comment]
> i'm using _gen_installed_app_list by default should this be trying to build the double ID code list??

No, that generates only the numeric id list.

**Comment by jaruba** [comment]
I'm not sure if this change is a good idea btw:
https://github.com/jaruba/ha-samsungtv-tizen/pull/75/files#diff-d7dec70a8f2cbc2ba0981dc6616635c3R81-R82
it might have unexpected consequences..

Have you tested these changes for some time? Did you notice significant improvement in state updates? Does the on / off state history seem correct?

**Comment by jaruba** [comment]
I released v1.5.0 which includes your changes

**Pull request merged**
