### PR TITLE
Fix I/O in loop, improved auto app detection, optimistic updates

### PR DESCRIPTION
**Pull request by mcc05**
Try again, fixes that work for me, thanks for the great code!

### CODE REVIEW

**Comment by jaruba** [comment]
Thank you, I will look this over and test it asap.

**Comment by mcc05** [comment]
@jaruba happy to help out where I can :), seems ok I've run it all day, however I am only using the ping method and not smartthings. I've added a check around the vol up/down to make sure it cant go under 0 or over 1, and I have had one 
"WARNING (MainThread) [homeassistant.helpers.entity] Updating state for media_player.kitchen_tv (<class 'custom_components.samsungtv_tizen.media_player.SamsungTVDevice'>) took 0.848 seconds. Please report it to the custom component author." ,so may have to look to may the update function faster

**Comment by jaruba** [comment]
I've had a chance to test this, and it seems to work well. I'll merge and make a new release.

**Comment by jaruba** [comment]
I released v1.4.7 with your changes.

**Pull request merged**
